UnaToolsGestao/UnaToolsGestao/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('tools.urls')),
    url(r'^', include('unazap.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

UnaToolsGestao/tools/urls.py
from django.conf.urls import url
from . import views
from . import webhooks
from . import gerador_contrato
from . import validacao_ajax
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy


app_name = 'tools'

urlpatterns = [

    #Weebhooks
    url(r'^ac_webhook_cadastro_klick$', webhooks.ac_webhook_cadastro_klick, name='ac_webhook_cadastro_klick'),
    url(r'^ac_webhook_cadastro_klick_degust$', webhooks.ac_webhook_cadastro_klick_degust, name='ac_webhook_cadastro_klick_degust'),

    url(r'^ac_webhook_contrato$', webhooks.ac_webhook_contrato, name='ac_webhook_contrato'),
    #Internal
    url(r'^visualizar_contrato/(?P<param>[\w{}.-]{0,200})/$', views.visualizar_contrato, name='visualizar_contrato'),
    url(r'^consultar_cliente$', views.consultar_cliente.as_view(), name='consultar_cliente'),
    url(r'^confirmar_dados$', views.confirmar_dados.as_view(), name='confirmar_dados'),
    url(r'^confirmar_dados_branco$', views.confirmar_dados_branco.as_view(), name='confirmar_dados_branco'),
    url(r'^confirmar_servico$', views.confirmar_servico.as_view(), name='confirmar_servico'),
    url(r'^escolher_servico$', views.escolher_servico.as_view(), name='escolher_servico'),
    url(r'^generate_pdf$', views.generate_pdf.as_view(), name='generate_pdf'),
    url(r'^concluido$', views.concluido.as_view(), name='concluido'),
    url(r'^visualizar_contrato$', views.visualizar_contrato.as_view(), name='visualizar_contrato'),
    url(r'^download_contrato$', views.download_contrato.as_view(), name='download_contrato'),
    #Index
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.index.as_view(), name='index'),
    url(r'^login$', views.index.as_view(), name='index'),
    url(r'^logout$', views.logout_view, name='logout'),


    url(r'^contracts/$', login_required(views.allcontracts.as_view()), name='contracts'),
    url(r'^contracts/(?P<pk>\d+)/$', login_required(views.confirmar_dados.as_view()), name='contractdetails'),
    #Validações
    url(r'^testevalidate$', views.testevalidate, name='testevalidate'),
    url(r'^validar_cpf/$', validacao_ajax.validar_cpf, name='validar_cpf'),
    url(r'^validar_cep/$', validacao_ajax.validar_cep, name='validar_cep'),
    url(r'^validar_data_nascimento/$', validacao_ajax.validar_data_nascimento, name='validar_data_nascimento'),
]

UnaToolsGestao/tools/forms.py
from django import forms
from localflavor.br.forms import BRCPFField, BRZipCodeField
from .models import Contrato


class ContratoFormAdmin(forms.ModelForm):
   cpf = BRCPFField(label="cpf")
   cep = BRZipCodeField(label="cep")

   class Meta:
       model = Contrato
       fields = '__all__'

UnaToolsGestao/tools/views.py
 # -*- coding: utf-8 -*-
 #Python Imports
import json
import os
from datetime import date
import datetime
import requests
import time
#Django Imports
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse,Http404
from django.conf import settings
from django.views import View
from django.utils import timezone
from django.template.loader import get_template
#Aplications Imports
from .models import Contrato, Turma, Tag, Transaction
from .forms import ContratoFormAdmin
from .choices import ESTADOS, ESTADO_CIVIL
from django.contrib.auth import authenticate, login
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout

class allcontracts(ListView):
    template_name = 'contracts_list.html'
    model = Contrato
    queryset = Contrato.objects.all().filter(assinado=False)

class index(View):
    template_name = 'login.html'

    def get(self, request,*args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        print(request.POST)
        if request.POST:
            email = request.POST['email']
            pwd = request.POST['senha']
            user = authenticate(request, username=email, password=pwd)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('contracts')
            else:
                return render(request, self.template_name, {'messages' : 'messages', 'email':email})
        return render(request, self.template_name, {})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')
    # Redirect to a success page.

#opcao com consulta de cliente por email
class consultar_cliente(View):
    template_name = 'index_base.html'
    form_class = ContratoFormAdmin

    def get(self, request,*args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        form = self.form_class()
        return render(request, self.template_name, { 'form' : form})

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        param = request.POST['email']
        if param:
            if Contrato.objects.filter(email=param).first():
                request.session['contrato_id']= str(Contrato.objects.filter(email=param).first().id)
                transaction = Transaction.objects.create(contrato=Contrato.objects.filter(email=param).first())
                return HttpResponseRedirect('confirmar_dados')
            else:
                return render(request, self.template_name, {'messages' : 'messages', 'email':param})
        return render(request, self.template_name, { 'form' : self.form_class()})


class confirmar_dados_branco(View):
    template_name = 'dados-contrato-branco.html'
    form_class = ContratoFormAdmin

    def get(self, request,*args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        return render(request, self.template_name, { 'form' : self.form_class(), 'estadolist': ESTADOS,'estadocivillist': ESTADO_CIVIL})

    def post(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        if request.POST:
            contrato_novo=Contrato.objects.create(email=request.POST['email'],
                              contratante = request.POST['contratante'],
                              rg=request.POST['rg'], cpf=request.POST['cpf'],
                              endereco=request.POST['endereco'],
                              endereco_cidade=request.POST['cidade'],endereco_uf= request.POST['estado'],
                              cep=request.POST['cep'], telefone=request.POST['telefone'],profissao=request.POST['profissao'],
                              endereco_bairro=request.POST['bairro'], complemento_endereco=request.POST['complemento'],
                              numero_endereco=request.POST['numero'], estado_civil=request.POST['estadocivil'],
                              data_nascimento=data_nasc_format(request.POST['data_nascimento']))
            contrato_novo.save()

            request.session['contrato_id']= str(contrato_novo.id)
            transaction = Transaction.objects.create(contrato=Contrato.objects.filter(id=contrato_novo.id).first())
            return HttpResponseRedirect('escolher_servico')
        return render(request, self.template_name, {})


class confirmar_dados(View):
    template_name = 'dados-contrato.html'
    form_class = ContratoFormAdmin

    def get_sigla_codigo(self,contrato):
        if contrato.endereco_uf:
            for estado in ESTADOS:
                if estado[0]==contrato.endereco_uf:
                    return estado[0]
        return ""

    def get_estado_civil(self,contrato):
        if contrato.estado_civil:
            for estado_civil in ESTADO_CIVIL:
                if estado_civil[0]==contrato.estado_civil:
                    return estado_civil[0]
        return ""

    def get(self, request,*args, **kwargs):

        contrato=Contrato.objects.filter(id=self.kwargs.get('pk')).first()

        if not contrato:
            return HttpResponseRedirect('consultar_cliente')

        request.session['contrato_id']= str(contrato.id)
        transaction = Transaction.objects.create(contrato=contrato)
        return render(request, self.template_name, { 'form' : self.form_class(), 'contratante': contrato.contratante, 'email': contrato.email,
                        'rg': contrato.rg, 'cpf': contrato.cpf,'endereco': contrato.endereco,
                        'cidade': contrato.endereco_cidade,'estadolist': ESTADOS,
                        'bairro': contrato.endereco_bairro, 'cep': contrato.cep,'complemento': contrato.complemento_endereco,
                        'numero': contrato.numero_endereco,'estadocivillist': ESTADO_CIVIL,'profissao': contrato.profissao,
                        'telefone': contrato.telefone, 'data_nascimento': contrato.data_nascimento,
                        'selected_opc_est': self.get_sigla_codigo(contrato),
                        'selected_opc_est_civil': self.get_estado_civil(contrato)})

    def post(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        contrato=Contrato.objects.filter(id=request.session.get('contrato_id')).first()

        if request.POST:
            contrato_atualizado=Contrato.objects.filter(id=request.session.get('contrato_id')).update(email=contrato.email,
                              contratante = request.POST['contratante'],
                              rg=request.POST['rg'], cpf=request.POST['cpf'],
                              endereco=request.POST['endereco'],
                              endereco_cidade=request.POST['cidade'],endereco_uf= request.POST['estado'],
                              cep=request.POST['cep'], telefone=request.POST['telefone'],profissao=request.POST['profissao'],
                              endereco_bairro=request.POST['bairro'], complemento_endereco=request.POST['complemento'],
                              numero_endereco=request.POST['numero'], estado_civil=request.POST['estadocivil'],
                              data_nascimento=data_nasc_format(request.POST['data_nascimento']))

            return HttpResponseRedirect('escolher_servico')
        return HttpResponseRedirect('consultar_cliente')


class escolher_servico(View):
    template_name = 'escolher-servico.html'
    form_class = ContratoFormAdmin

    def get_cursos(self):
        cursos = Tag.objects.all()
        lista_cursos = [('','Selecione o Curso')]
        # lista_cursos = []
        for c in cursos:
            lista_cursos.append((int(c.id), c))
        return lista_cursos


    def get(self, request,*args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        contrato=Contrato.objects.filter(id=request.session.get('contrato_id')).first()

        if not contrato:
            return HttpResponseRedirect('consultar_cliente')

        data_atual=date.today()
        return render(request, self.template_name, { 'form' : self.form_class(), 'email': contrato.email, 'lista_cursos': self.get_cursos()})

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/?next=%s' % request.path)

        contrato=Contrato.objects.filter(id=request.session.get('contrato_id')).first()

        if not contrato:
            return HttpResponseRedirect('consultar_cliente')

        if request.POST:
            contrato_atualizado=Contrato.objects.filter(id=request.session.get('contrato_id')).update(
                              curso=Tag.objects.filter(id=request.POST['cursos']).first(),
                              extra_bonus = request.POST['curso_desc'])

            return HttpResponseRedirect('confirmar_servico')

        return render(request, self.template_name)


class confirmar_servico(View):
    template_name = 'dados-servico.html'
    form_class = ContratoFormAdmin

    def get_turmas_abertas(self, curso_id):
        turmas_ativas = Turma.objects.filter(status_turma=False, curso=curso_id)
        lista_turmas = [('','Selecione a Turma')]
        for turma in turmas_ativas:
            lista_turmas.append((int(turma.id), turma))
        return lista_turmas

    def querydict_to_string(self, query_dict, filter_name):
        result=' '
        for key in query_dict.keys():

UnaToolsGestao/tools/templates/base_site.html
{% load static %}
<html>
    <head>
       <meta charset="UTF-8">
       <title>2minutos</title>
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <meta property="og:description" content="Fundada na cidade de Salvador em 2016, inicialmente como uma empresa de rastreamento especializada em projetos customizados, gestão de frotas e rastreamento de veículos.">
       <meta name="description" content="Fundada na cidade de Salvador em 2016, inicialmente como uma empresa de rastreamento especializada em projetos customizados, gestão de frotas e rastreamento de veículos.">
       <script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
       <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}">
       <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
       <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/css/bootstrapValidator.min.css"/>
       <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/js/bootstrapValidator.min.js"></script>
       <script type='text/javascript' src="https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>
       {% block javascript %}
       {% endblock %}
    </head>
    <body>
        <!-- HEADER -->
        {% block header %}
        {% endblock %}
        <!-- FORMULARIO LARANJA - TODAS AS PÁGINAS -->
        {% block formlaranja %}
        {% endblock %}
        <!-- CONTEÚDO ESPECÍFICO DA PÁGINA -->
        {% block content %}
        {% endblock %}

        {% block footer %}
        <div class="content">
        {% endblock %}
      
 </html>

UnaToolsGestao/tools/templates/contracts_list.html
{% load staticfiles %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
		<title>Todos os Contratos</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

			<link rel="icon" type="image/png" href="{% static 'images/iconpucco.png' %}"/>
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'vendor/noui/nouislider.min.css' %}">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<!--===============================================================================================-->

  </head>
  <body>
    {% include "menu.html" %}
    <div class="container-contact80">
        <div class="wrap-contact100">

          <span class="contact100-form-title-dois">
            Contratos Recentes
          </span>
    				<div class="list-group">
    					{% for contrato in contrato_list %}
    					  <a href="{% url 'tools:contracts' %}{{contrato.pk}}" class="list-group-item list-group-item-action flex-column align-items-start">
    					    <div class="d-flex w-100 justify-content-between">
    					      <h5 class="mb-1">{{ contrato }}</h5>
    					      <small>{{ contrato.data_recebimento }}</small>
    					    </div>
    					    <p class="mb-1">{{ contrato.telefone }} | {{ contrato.email }}</p>
    					    <small>Consultor(a): {% if contrato.consultor is not none %}{{ contrato.consultor }}{% else %}A definir{%endif %}</small>
    					  </a>
    					{% empty %}
    					    <li>Sem Contratos Pendentes no Momento.</li>
    					{% endfor %}
    				</div>

      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/masks.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </body>
</html>

UnaToolsGestao/tools/templates/generate-wait.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
		<title>Gerando Contrato...</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

			<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/fonts/iconic/css/material-design-iconic-font.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/noui/nouislider.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/css/util.css">
			<link rel="stylesheet" type="text/css" href="static/css/main.css">
		<!--===============================================================================================-->

  </head>
  <body>
      <div class="container-contact100">

        <div class="spinner-grow" role="status" name="carregandoinfo">
          <span class="sr-only">Loading...</span>
        </div>
        <script>
        setTimeout(function(){
            $(".spinner-grow").fadeOut("slow");
        }, 3000);
        setTimeout(function(){
           window.location.href = '{% url "tools:concluido" %}';
        }, 3000);
        </script>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/masks.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </body>
</html>

UnaToolsGestao/tools/templates/generated.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
		<title>Contrato Gerado com Sucesso</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

			<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/fonts/iconic/css/material-design-iconic-font.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/vendor/noui/nouislider.min.css">
		<!--===============================================================================================-->
			<link rel="stylesheet" type="text/css" href="static/css/util.css">
			<link rel="stylesheet" type="text/css" href="static/css/main.css">
		<!--===============================================================================================-->

  </head>
  <body>
    {% include "menu.html" %}   
      <div class="container-contact100">
          <div class="wrap-contact100">
            <h1 style="text-align:center">Contrato Gerado com Sucesso!<h1/>
            </br>
            <div class="text-center">
              <a href="/visualizar_contrato" class="btn btn-outline-secondary" role="button">Visualizar</a>
              <a href="/download_contrato" class="btn btn-outline-success" role="button">Baixar Contrato</a>
              <a href="https://app.clicksign.com/" class="btn btn-outline-info" role="button">Abrir ClickSign</a>
            </div>
          </div>
      </div>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/masks.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </body>
</html>